### ISSUE TITLE
Impossible to access the website now

### ISSUE THREAD

**Issue by LoganDark** [Draylar/minecraft-mapper#10]
https://draylar.github.io/minecraft-mapper (or wherever this used to be) redirects to your website that no longer hosts the tool.

Please I don't want to download proguard shit :(

**Comment by Draylar** [comment]
@LoganDark I personally use https://shartte.github.io/minecraft-mapper/ now, which is a fork of my project that downloads all the mapping files in your browser (rather than requiring an external NodeJS server like this project does). I'd recommend using that unless you want to host the NodeJS server on your own machine to cache mapping files.
